# Generated by Django 5.0.14 on 2026-08-19 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('method', models.CharField(choices=[('CASH', 'Naqd'), ('CARD', 'Karta (terminal)'), ('CLICK', 'Click'), ('BANK_TRANSFER', "Bank o'tkazmasi")], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('PAID', "To'landi"), ('FAILED', 'Muvaffaqiyatsiz'), ('REFUNDED', 'Qaytarildi'), ('PARTIALLY_PAID', "Qisman to'landi")], default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
            },
        ),
        migrations.CreateModel(
            name='ClickTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_trans_id', models.CharField(db_index=True, max_length=50)),
                ('click_paydoc_id', models.CharField(blank=True, max_length=50)),
                ('merchant_trans_id', models.CharField(db_index=True, max_length=50)),
                ('action', models.PositiveSmallIntegerField(help_text='0=Prepare, 1=Complete')),
                ('error_code', models.IntegerField(default=0)),
                ('raw_request', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_transactions', to='payments.paymentstatus')),
            ],
            options={
                'verbose_name': 'Click tranzaksiyasi',
                'verbose_name_plural': 'Click tranzaksiyalari',
            },
        ),
    ]
