# -*- coding: utf-8 -*-
"""
1000 ta ruscha so'zlarning to'liq, mukammal va xatosiz o'zbekcha tarjimalari.
"""

TRANSLATIONS_ALL = {
    # Remaining 292 words
    "рад": "xursand, shod",
    "верить": "ishonmoq",
    "материал": "material, xomashyo, mato",
    "вести": "boshlamoq, olib bormoq",
    "звать": "chaqirmoq, nomlamoq",
    "прийтись": "to'g'ri kelmoq, majbur bo'lmoq",
    "решение": "qaror, yechim",
    "над": "ustida, tepasida",
    "основной": "asosiy, bosh",
    "принцип": "tamoyil, prinsip",
    "российский": "rossiya, rossiyalik",
    "возможный": "mumkin bo'lgan, ehtimoliy",
    "принять": "qabul qilmoq",
    "терять": "yo'qotmoq",
    "искать": "qidirmoq, izlamoq",
    "том": "o'sha (kelishikda), jild (kitob)",
    "читать": "o'qimoq",
    "группа": "guruh",
    "карта": "xarita, karta",
    "нельзя": "mumkin emas, taqiqlanadi",
    "точка": "nuqta",
    "далее": "keyinroq, davomi",
    "следовать": "ergashmoq, amal qilmoq",
    "убить": "o'ldirmoq",
    "эй": "hey, hoy",
    "данный": "ushbu, mazkur",
    "никакой": "hech qanday, hech bir",
    "пара": "juft, juftlik, ikki dona",
    "уверенный": "ishonchi komil, dadil",
    "добавить": "qo'shmoq",
    "нога": "oyoq",
    "довольно": "yetarli, ancha, birmuncha",
    "доллар": "dollar ($)",
    "область": "viloyat, soha",
    "против": "qarshi",
    "сын": "o'g'il, farzand",
    "добрый": "mehribon, ezgu, xayrli",
    "проходить": "o'tmoq, bo'lib o'tmoq",
    "сильный": "kuchli, baquvvat",
    "бывать": "bo'lib turmoq, uchramoq",
    "долго": "uzoq vaqt",
    "комментарий": "izoh, sharh",
    "процент": "foiz (%)",
    "умереть": "vafot etmoq, o'lmoq",
    "красный": "qizil (rang)",
    "снимать": "yechmoq, suratga olmoq",
    "внутри": "ichida, ichkarida",
    "дорогой": "qimmatbaho, qadrli, aziz",
    "крутой": "zo'r, qoyilmaqom, tik",
    "сообщение": "xabar, ma'lumot",
    "еда": "ovqat, taom",
    "вроде": "kabi, go'yoki, o'xshash",
    "всего": "jami, bor-yo'g'i",
    "жена": "xotin, rafiqa, ayoli",
    "пример": "misol, namuna",
    "выходить": "chiqmoq",
    "завтра": "ertaga",
    "мать": "ona",
    "поздно": "kech, kech qolib",
    "принимать": "qabul qilmoq",
    "русский": "ruscha, rus tili/odami",
    "земля": "yer, tuproq, zamin",
    "менее": "kamroq, kam",
    "показывать": "ko'rsatmoq",
    "приятный": "yoqimli, shirin",
    "девочка": "qizcha, qiz bola",
    "полностью": "to'liq, to'la-to'kis",
    "провести": "o'tkazmoq (tadbir/vaqt)",
    "связать": "bog'lamoq, ulamoq",
    "строить": "qurmoq, bino qilmoq",
    "плюс": "ortiqcha, plyus, afzallik",
    "собственный": "o'zining, xususiy",
    "установить": "o'rnatmoq, belgilamoq",
    "есть": "yemoq, bor (mavjud)",
    "любимый": "sevimli, yoqimli",
    "низкий": "past, past bo'yli",
    "подобный": "shunga o'xshash, bunday",
    "прошлый": "o'tgan, avvalgi",
    "новость": "yangilik",
    "разве": "nahotki, rostdanmi",
    "ссылка": "havola (link)",
    "хватать": "yetmoq, ushlab olmoq",
    "задача": "topshiriq, vazifa, masala",
    "менять": "almashtirmoq, o'zgartirmoq",
    "рассказывать": "so'zlab bermoq",
    "мера": "chora, o'lchov",
    "означать": "anglatmoq, bildirish",
    "позволять": "imkon bermoq",
    "хоть": "hech bo'lmasa, garchi",
    "метр": "metr",
    "поскольку": "chunki, shu sababli",
    "странный": "g'alati, ajablanarli",
    "целый": "butun, to'liq",
    "всякий": "har qanday, turli",
    "существовать": "mavjud bo'lmoq, yashamoq",
    "что-нибудь": "biror narsa",
    "извинить": "kechirmoq",
    "правильный": "to'g'ri, durust",
    "счастливый": "baxtiyor, baxtli",
    "чувство": "tuyg'u, hissiyot",
    "изменить": "o'zgartirmoq, xiyonat qilmoq",
    "муж": "er, turmush o'rtog'i",
    "особенно": "ayniqsa, xususan",
    "пре": "o'ta, juda (old qo'shimcha)",
    "течение": "oqim, davomiylik",
    "где-то": "qayerdadir, chamasi",
    "использование": "foydalanish, qo'llash",
    "название": "nom, sarlavha",
    "представлять": "tasavvur etmoq",
    "сестра": "opa, singil",
    "камера": "kamera, fotoapparat",
    "скорее": "tezroq, aksincha",
    "тяжелый": "og'ir, mashaqqatli",
    "движение": "harakat, qatnov",
    "курс": "kurs, yo'nalish",
    "называться": "atalmoq, nomlanmoq",
    "пить": "ichmoq",
    "примерно": "taxminan, chamasi",
    "предложение": "taklif, gap (grammatika)",
    "ум": "aql, idrok, zehn",
    "военный": "harbiy",
    "здравствовать": "omon bo'lmoq (salomlashish)",
    "список": "ro'yxat",
    "учиться": "o'qimoq, tahsil olmoq",
    "мысль": "fikr, o'y",
    "президент": "prezident",
    "спрашивать": "so'ramoq",
    "отсюда": "bu yerdan",
    "привести": "keltirmoq, olib kelmoq",
    "средний": "o'rtacha, o'rta",
    "честно": "rostgo'ylik bilan, to'g'risi",
    "близкий": "yaqin, qadrdon",
    "вчера": "kecha, kechagi kun",
    "нормально": "yaxshi, joyida, normal",
    "блин": "quymoq, attang (og'zaki)",
    "голос": "ovoz, tovush",
    "квартира": "xonadon, kvartira",
    "носить": "taqmoq, kiyib yurmoq",
    "рабочий": "ishchi, ishga oid",
    "столько": "shuncha, shunchalik ko'p",
    "шанс": "imkoniyat, fursat",
    "большинство": "ko'pchilik, aksariyat",
    "готовить": "pishirmoq, tayyorlamoq",
    "класть": "qo'ymoq (yotqizib)",
    "объект": "ob'yekt, bino, narsa",
    "покупать": "xarid qilmoq",
    "ради": "uchun, haqqi-hurmati",
    "штука": "dona, narsa, buyum",
    "бросить": "tashlamoq, uloqtirmoq",
    "дерево": "daraxt, yog'och",
    "клиент": "mijoz, xaridor",
    "поле": "dala, maydon",
    "различный": "har xil, turfa",
    "страшный": "qo'rqinchli, mudhish",
    "элемент": "element, bo'lak",
    "допустить": "yo'l qo'ymoq, ruxsat bermoq",
    "кнопка": "tugma, knopka",
    "ожидать": "kutmoq, umid qilmoq",
    "полезный": "foydali, zararsiz",
    "район": "tuman, hudud",
    "суд": "sud, mahkama",
    "верный": "sodiq, to'g'ri",
    "дочь": "qiz (farzand)",
    "кожа": "teri, charm",
    "ой": "voy, oh",
    "режим": "rejim, tartib",
    "товар": "mahsulot, buyum",
    "версия": "versiya, talqin",
    "пользователь": "foydalanuvchi",
    "трудный": "qiyin, murakkab",
    "кровь": "qon",
    "снять": "yechmoq, ijaraga olmoq",
    "убивать": "o'ldirmoq",
    "реальный": "haqiqiy, real",
    "соответственно": "mos ravishda, shunga ko'ra",
    "благодаря": "tufayli, sababli, sharofati bilan",
    "метод": "usul, metod",
    "речь": "nutq, so'z",
    "бой": "jang, olishuv",
    "встречаться": "uchrashib turmoq",
    "род": "jins (grammatika), avlod, urug'",
    "выиграть": "yutmoq, g'olib bo'lmoq",
    "ход": "yurish, harakatlanish",
    "здоровый": "sog'lom, baquvvat",
    "роль": "rol, vazifa",
    "стиль": "uslub, stil",
    "великий": "buyuk, ulug'",
    "невозможный": "imkonsiz, ilojsiz",
    "поддержка": "qo'llab-quvvatlash, madad",
    "суть": "mohiyat, asosiy ma'no",
    "вернуть": "qaytarib bermoq",
    "господин": "janob",
    "сэр": "ser (murojaat)",
    "энергия": "quvvat, energiya",
    "иначе": "aks holda, boshqacha",
    "определенный": "aniq, ma'lum bir",
    "серия": "qism, seriya",
    "ясный": "ochiq, ravshan, oydin",
    "видно": "ko'rinib turibdi, aftidan",
    "двигаться": "harakatlanmoq, siljimoq",
    "инструмент": "asbob, uskuna, vosita",
    "организация": "tashkilot, uyushma",
    "скорость": "tezlik, sur'at",
    "тратить": "sarflamoq, xarajat qilmoq",
    "действовать": "harakat qilmoq, ta'sir qilmoq",
    "основа": "asos, poydevor",
    "практически": "amalda, deyarli",
    "угол": "burchak",
    "доктор": "shifokor, doktor",
    "коротко": "qisqacha",
    "удар": "zarba, urish",
    "возвращаться": "qaytib kelmoq",
    "дома": "uyda",
    "относиться": "munosabatda bo'lmoq",
    "управление": "boshqaruv, ma'muriyat",
    "положение": "holat, vaziyat, nizom",
    "сцена": "sahna",
    "больший": "kattaroq",
    "появляться": "paydo bo'lib turmoq",
    "рыба": "baliq",
    "таки": "baribir, shunda ham",
    "хватить": "yetarli bo'lmoq",
    "век": "asr (100 yil)",
    "код": "kod, maxfiy raqam",
    "операция": "operatsiya, amaliyot",
    "текст": "matn, tekst",
    "черт": "jin, iblis (og'zaki)",
    "кое-что": "ba'zi narsalar, allanima",
    "придумать": "o'ylab topmoq",
    "смеяться": "kulmoq",
    "чистый": "toza, ozoda",
    "вниз": "pastga, quyiga",
    "зависеть": "bog'liq bo'lmoq",
    "открывать": "ochmoq",
    "приложение": "ilova (mobil/dastur)",
    "собрать": "yig'moq, to'plamoq",
    "чувак": "jo'ra, og'ayni, oshna",
    "минус": "kamchilik, minus",
    "продажа": "sotuv, savdo",
    "согласный": "rozi, undosh (tovush)",
    "технология": "texnologiya",
    "вызвать": "chaqirmoq",
    "мистер": "janob, mister",
    "планировать": "rejalashtirmoq",
    "экран": "ekran, monitor",
    "выполнять": "bajarmoq",
    "заставить": "majburlamoq",
    "намного": "ancha, ancha ko'p",
    "победить": "g'alaba qozonmoq",
    "просмотр": "ko'rish, tomosha",
    "социальный": "ijtimoiy",
    "эффект": "samara, ta'sir, effekt",
    "гораздо": "ancha, ancha ko'proq",
    "требоваться": "talab qilinmoq",
    "государственный": "davlatga qarashli",
    "зеленый": "yashil (rang)",
    "настолько": "shunchalik, shu darajada",
    "поддерживать": "qo'llab-quvvatlamoq",
    "разговаривать": "suhbatlashmoq",
    "указать": "ko'rsatmoq, belgilamoq",
    "граница": "chegara",
    "зрение": "ko'rish qobiliyati",
    "начинаться": "boshlanmoq",
    "подписать": "imzolamoq",
    "старший": "katta, yoshi ulug'",
    "украина": "Ukraina",
    "детский": "bolalar, bolalarga oid",
    "немножко": "ozgina, bir oz",
    "позиция": "mavqe, pozitsiya, o'rin",
    "политика": "siyosat",
    "сантиметр": "santimetr (sm)",
    "ах": "oh, eh (undov)",
    "входить": "kirmoq",
    "заходить": "kirib o'tmoq",
    "корабль": "kema",
    "образование": "ta'lim, ma'lumot",
    "блок": "blok, qism",
    "кофе": "qahva, kofe",
    "обратно": "orqaga, qaytib",
    "здание": "bino, inshoot",
    "край": "chet, chekka, o'lka",
    "оставлять": "qoldirmoq",
    "правый": "o'ng, to'g'ri (haq)",
    "слой": "qatlam, qavat",
    "быстрый": "chaqqon, tezkor",
    "знак": "belgi, ishora",
    "служба": "xizmat, xizmat vazifasi",
    "вверх": "yuqoriga, tepaga",
    "знакомиться": "tanishmoq",
    "куча": "to'da, uyum",
    "собственно": "aslida, o'z navbatida",
    "веселый": "quvnoq, xushchaqchaq"
}
