# Generated by Django 5.0.14 on 2026-08-19 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('language', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=2)),
                ('role', models.CharField(choices=[('GUEST', 'Mehmon'), ('OPERATOR', 'Operator'), ('MANAGER', 'Menejer'), ('ADMIN', 'Administrator'), ('SUPERADMIN', 'Bosh administrator')], db_index=True, default='GUEST', max_length=20)),
                ('is_blocked', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('linked_admin_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram foydalanuvchi',
                'verbose_name_plural': 'Telegram foydalanuvchilar',
                'indexes': [models.Index(fields=['telegram_id'], name='accounts_te_telegra_50ceb1_idx'), models.Index(fields=['role'], name='accounts_te_role_2c8e4d_idx'), models.Index(fields=['is_blocked'], name='accounts_te_is_bloc_150c3c_idx')],
            },
        ),
    ]
